#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Loads the Docker image from the container registry and then runs the following steps:
#
#  1. Copy Gradle cache
#  2. Extract tarball
#  3. Copy .git dir
#  4. Build debug APK and run checkstyle checks (suppress failure if check fails)
#  5. Save reports to GCS
#  6. Update badge status and fail the build if any errors were encountered during step 4
#  7. Compress Gradle files
#  8. Save tarball
#
#  NOTE: APKs are saved to GCS only if the build passes
#
# Based on https://github.com/GoogleCloudPlatform/cloud-builders-community

steps:

  # Copy the cache from last build
  - name: 'gcr.io/cloud-builders/gsutil'
    id: copy_build_cache
    # we use rsync and not cp so that this step doesn't fail the first time it's run
    args: ['rsync', 'gs://${_CACHE_BUCKET}/', '/build_cache']
    volumes:
      - name: 'build_cache'
        path: '/build_cache'

  # Extract the copied tar file
  - name: 'gcr.io/$PROJECT_ID/android:base'
    id: extract_build_cache
    waitFor: ['copy_build_cache']
    # This might fail the first time, but that's okay
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar xpzf /build_cache/cache.tgz -C /build_cache || echo "No cache found."
    volumes:
      - name: 'build_cache'
        path: '/build_cache'

  # Copy .git directory to workspace.
  # This is needed by gitVersioner plugin for auto-generating version code and version name.
  #
  # TODO: Remove this step when .git can be explicitly included in the tarball using .gcloudignore
  # https://github.com/GoogleCloudPlatform/cloud-builders/issues/401
  - name: 'gcr.io/cloud-builders/git'
    id: copy_git_directory
    waitFor: ['extract_build_cache']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone --branch master $_HEAD_REPO_URL tmp \
        && mv tmp/.git . \
        && rm -rf tmp

  # Build debug APK and run checkstyle checks
  - name: 'gcr.io/$PROJECT_ID/android:28'
    id: build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew assembleDebug && \
        ./gradlew checkCode || echo "fail" > /workspace/build-status.txt
    env:
      - 'GRADLE_USER_HOME=/build_cache/.gradle'
    waitFor: ['copy_git_directory']
    volumes:
      - name: 'build_cache'
        path: '/build_cache'

  # Save all reports to GCS
  - id: Save artifacts to GCS
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
      - cp -r gnd/build/reports gs://${_ARTIFACT_BUCKET}/$BRANCH_NAME-$BUILD_ID/reports || echo "Reports not generated"

  # Update status badge and fail build if errors were found in "build" step
  - id: Bubble build result
    name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update build status if running on master branch
        if [[ "${_PUSH_TO_MASTER}" ]]; then
          if [[ $(< /workspace/build-status.txt) == "fail" ]]; then
            gsutil cp cloud-builder/failure.svg gs://${_CACHE_BUCKET}/status.svg
          else
            gsutil cp cloud-builder/success.svg gs://${_CACHE_BUCKET}/status.svg
          fi

          # Make file public readable
          gsutil acl ch -u AllUsers:R gs://${_CACHE_BUCKET}/status.svg
        fi

        # Delayed build fail
        if [[ $(< /workspace/build-status.txt) == "fail" ]]; then
          echo "Build failed."
          echo "Reports uploaded to https://console.cloud.google.com/storage/browser/${_ARTIFACT_BUCKET}/$BRANCH_NAME-$BUILD_ID/"
          exit 1
        fi

  # Compress the gradle build cache
  - name: 'gcr.io/$PROJECT_ID/android:base'
    id: compress_cache
    waitFor: ['build']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar cpvzf /build_cache/cache.tgz -C /build_cache /build_cache/.gradle
    volumes:
      - name: 'build_cache'
        path: '/build_cache'

  # Store the build cache
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '/build_cache/cache.tgz', 'gs://${_CACHE_BUCKET}/cache.tgz']
    waitFor: ['compress_cache']
    volumes:
      - name: 'build_cache'
        path: '/build_cache'

# Save the APKs and reports
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/$BRANCH_NAME-$BUILD_ID'
    paths: ['gnd/build/outputs/apk/*/*.apk']

timeout: 1800s
